# Generated by Django 5.2.3 on 2025-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Almacén'), ('office', 'Oficina'), ('drugstore', 'Farmacia')], max_length=20),
        ),
    ]
