# Generated by Django 5.2.3 on 2025-06-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0003_assetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('pc', 'PC'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('nobreak', 'Nobreak'), ('printer', 'Impresora'), ('network', 'Equipo de Red'), ('peripheral', 'Periférico'), ('server', 'Servidor'), ('other', 'Otro')], max_length=20, verbose_name='Categoría'),
        ),
    ]
