# Generated by Django 5.2.3 on 2025-06-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0004_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
    ]
