# Generated by Django 5.2.3 on 2025-06-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0005_asset_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
    ]
