# Generated by Django 5.2.3 on 2025-06-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0006_asset_brand_asset_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='image',
        ),
    ]
