# Generated by Django 5.2.3 on 2025-06-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0007_remove_asset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterResponsibility', models.ImageField(upload_to='letterResponsibility/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterResponsibilitys', to='FA01.asset')),
            ],
        ),
    ]
