# Generated by Django 5.2.3 on 2025-06-23 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0008_responsibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name': 'Responsiva', 'verbose_name_plural': 'Responsivas'},
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='letterResponsibility',
        ),
        migrations.AddField(
            model_name='responsibility',
            name='letter_responsibility',
            field=models.ImageField(default=1, upload_to='letter_responsibility/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('in_use', 'En Uso'), ('maintenance', 'En Mantenimiento'), ('repair', 'En Reparación'), ('retired', 'Retirado'), ('lost', 'Perdido')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_responsibilities', to='FA01.asset'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
