# Generated by Django 5.2.3 on 2025-06-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0009_alter_responsibility_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='movement',
            field=models.CharField(choices=[('location', 'Cambio de Ubicación'), ('assignment', 'Cambio de Responsable'), ('maintenance', 'Envío a Mantenimiento'), ('return', 'Retorno de Mantenimiento'), ('retirement', 'Dado de Baja')], default=1, max_length=20, verbose_name='Movimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='to_user_external',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
