# Generated by Django 5.2.3 on 2025-06-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0010_movement_movement_movement_to_user_external_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='to_user_external',
            new_name='assigned_to_name',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='to_user',
        ),
    ]
