# Generated by Django 5.2.3 on 2025-06-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA01', '0011_rename_to_user_external_movement_assigned_to_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Nombre del responsable (puede no ser usuario del sistema)', max_length=100, null=True),
        ),
    ]
